import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
  localGlobLight: {
    color: '#606060',
    fontWeight: 'bold',
  },
  localGlobDark: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  containerDark: {
    backgroundColor: '#F8F8F8',
    width: '95%',
    borderRadius: 6,
    alignSelf: 'center',
    marginTop: 20,
    paddingTop: 10,
  },
  containerLight: {
    backgroundColor: '#555555',
    width: '95%',
    borderRadius: 6,
    alignSelf: 'center',
    marginTop: 20,
    paddingTop: 10,
  },
  cardImage: {
    height: 100,
    width: 100,
  },
  imageAndButtonHolder: {
    flexDirection: 'row',
  },

  addArticleTextLight: {
    color: '#606060',
    fontWeight: 'bold',
    fontSize: 18,
    paddingTop: 5,
    paddingBottom: 5,
    alignSelf: 'center',
    marginTop: 20,
    marginLeft: 20,
  },
  addArticleTextDark: {
    color: '#F8F8F8',
    fontWeight: 'bold',
    fontSize: 18,
    paddingTop: 5,
    paddingBottom: 5,
    alignSelf: 'center',
    marginTop: 20,
    marginLeft: 20,
  },

  clearPhotoCircle: {
    borderWidth: 1,
    borderColor: 'red',
    width: 20,
    height: 20,
    borderRadius: 20 / 2,
    backgroundColor: 'transparent',
    bottom: 10,
    justifyContent: 'center',
  },
  clearImageButtonText: {
    color: 'red',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 12,
  },
  thumbnailButton: {
    borderColor: '#1890ff',
    borderWidth: 1,
    borderRadius: 5,
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
    height: 30,
  },
  thumbnailContainer: { width: '75%' },
  thumbnailButtonText: {
    color: '#1890ff',
  },
  input: {
    fontSize: 13,
    borderWidth: 1,
    borderColor: 'lightgray',
    borderRadius: 5,
    backgroundColor: 'white',
    paddingHorizontal: 10,
    height: 40,
    width: '75%',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    marginRight: 7,
  },
  descriptionInput: {
    fontSize: 13,
    borderWidth: 1,
    borderColor: 'lightgray',
    borderRadius: 5,
    backgroundColor: 'white',
    paddingHorizontal: 10,
    width: '75%',
    height: 150,
    textAlignVertical: 'top',
  },
  inputText: {
    color: 'gray',
  },
  instructionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
    marginRight: 5,
  },
  instructionTextLight: {
    fontWeight: 'bold',
    width: 95,
    color: '#606060',
    marginLeft: 5,
  },
  instructionTextDark: {
    fontWeight: 'bold',
    width: 95,
    color: '#F8F8F8',
    marginLeft: 5,
  },
  isRequiredSymbol: {
    color: 'red',
    marginLeft: 4,
  },
  radioFormContainer: {
    flexDirection: 'row',
    flex: 1,
  },
  hotNewsPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 5,
  },

  categoryContainer: {
    height: 120,
    width: '73%',
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderWidth: 1,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    alignSelf: 'flex-end',
    marginTop: -10,
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  categoryText: {
    color: 'gray',
    marginVertical: 5,
  },
  button: {
    backgroundColor: '#1890ff',
    borderColor: '#1890ff',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 10,
    alignSelf: 'flex-start',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    alignSelf: 'center',
  },
  nextPhaseCard: {
    alignSelf: 'center',
    marginTop: 25,
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 4,
    backgroundColor: 'white',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
    width: Dimensions.get('window').width / 1.2,
  },
  nextPhaseCardText: {
    marginLeft: 10,
    marginTop: 3,
    color: 'gray',
    fontSize: 16,
  },
  nextPhaseCardSubtext: {
    marginLeft: 5,
    marginTop: 3,
    color: 'gray',
    fontSize: 16,
    flexDirection: 'row',
  },
  nextPhaseContainer: {
    height: Dimensions.get('window').height / 0.5,
  },
  nextPhaseButton: {
    backgroundColor: '#1890ff',
    borderColor: '#1890ff',
    borderWidth: 1,
    borderRadius: 5,
    width: Dimensions.get('screen').width / 5,
    height: Dimensions.get('screen').height / 30,
    marginLeft: 20,
    marginTop: 10,
  },
  nextPhaseMainContent: {
    justifyContent: 'center',
    marginLeft: 35,
    marginTop: 5,
  },
  nextPhaseConfirmationHolder: {
    backgroundColor: 'white',
    height: Dimensions.get('screen').height / 15,
    width: Dimensions.get('screen').width / 3,
    marginLeft: 50,
    marginTop: 3,
    borderColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.3,
    shadowRadius: 9.51,
    elevation: 15,
  },
  nextPhaseConfirmationButton: {
    backgroundColor: 'white',
    borderColor: '#1890ff',
    borderWidth: 1,
    borderRadius: 5,
    width: Dimensions.get('screen').width / 10,
    height: Dimensions.get('screen').height / 40,
    marginLeft: 15,
    marginTop: 10,
  },
  nextPhaseConfirmationButtonText: {
    color: '#1890ff',
    alignSelf: 'center',
    fontSize: 14,
  },
  nextPhaseText: {
    color: 'gray',
    marginLeft: 5,
    marginTop: 3,
  },
  nextPhaseButtonsContainer: {
    flexDirection: 'row',
  },
  errorText: {
    color: 'red',
    marginTop: 10,
    paddingBottom: 20,
  },
  chosenTagsContainer: {
    width: 270,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'gray',
    backgroundColor: 'white',
    alignSelf: 'flex-end',
    marginRight: 30,
    bottom: 15,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tagStyle: {
    flexDirection: 'row',
    backgroundColor: 'gray',
    borderRadius: 5,
    justifyContent: 'center',
    padding: 5,
  },
  tagsContainer: {
    flexDirection: 'row',
    marginLeft: 5,
    marginTop: 5,
    paddingTop: 2,
    paddingBottom: 5,
    paddingLeft: 5,
  },
  tagText: {
    color: 'whitesmoke',
    fontWeight: 'bold',
    fontSize: 12,
  },
  tagXText: {
    color: 'whitesmoke',
    fontWeight: 'bold',
    fontSize: 12,
    marginLeft: 2,
  },
  activityContainer: {
    paddingTop: 3,
    flexDirection: 'row',
  },
  nextPhaseTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },

  articlesContainer: {
    width: '93%',
  },
  detailedDescription: {
    height: 100,
    borderWidth: 1,
    width: '80%',
    marginLeft: 20,
    marginTop: 10,
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderRadius: 5,
  },
});

export default styles;
