import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  generalOptionsContainer: {
    marginTop: '10%',
  },
  containerDark: {
    alignSelf: 'center',
    backgroundColor: '#555555',
    width: '90%',
    borderWidth: 1,
    borderRadius: 5,
  },
  containerLight: {
    alignSelf: 'center',
    backgroundColor: 'white',
    width: '90%',
    borderColor: 'white',
    borderWidth: 1,
    borderRadius: 5,
  },
  mainContentContainer: {
    marginTop: 10,
    marginLeft: 15,
    paddingBottom: 10,
  },
  primaryButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: '#1890ff',
    borderRadius: 5,
    width: '32%',
    height: 40,
    justifyContent: 'center',
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: 'white',
    borderRadius: 5,
    width: '32%',
    height: 40,
    justifyContent: 'center',
    marginLeft: 20,
  },
  secondaryButtonText: {
    color: '#1890ff',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  primaryButtonText: {
    color: 'white',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  userInfoContainer: {
    marginTop: 15,
    justifyContent: 'space-between',
  },
  headerButtonsContainer: {
    flexDirection: 'row',
  },
  inputStyle: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'white',
    width: '90%',
    height: 30,
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    flexDirection: 'row',
  },
  textDark: {
    paddingTop: 3,
    fontSize: 15,
    width: 180,
    color: 'white',
    fontWeight: 'bold',
  },
  textLight: {
    paddingTop: 3,
    fontSize: 15,
    width: 180,
    color: '#606060',
    fontWeight: 'bold',
  },
  dropDownButton: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'white',
    width: '70%',
    height: 30,
    padding: 5,
  },
  disabledDropDownButton: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    width: '70%',
    height: 30,
    marginRight: 10,
    padding: 5,
  },
  dropDownHolder: {
    width: 460,
    marginTop: 10,
  },
  userSecurityOptionsHolder: {
    borderWidth: 0.5,
    borderColor: 'gray',
    borderRadius: 4,
    width: '70%',
    justifyContent: 'center',
  },

  userSecurityOptionButton: {
    marginLeft: 5,
    marginTop: 5,
  },
  multilineInput: {
    marginTop: 10,
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'white',
    width: '90%',
    height: 60,
    marginRight: 10,
    padding: 5,
  },
  disableInput: {
    marginTop: 5,
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    width: '90%',
    height: 30,
    marginRight: 10,
    padding: 5,
  },
  disableMultiLineInput: {
    marginTop: 10,
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    width: '90%',
    height: 60,
    marginRight: 10,
    padding: 5,
  },
  categorieListContainer: {
    alignSelf: 'center',
    paddingBottom: 25,
    width: '80%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  userRegionsListButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: '#1890ff',
    borderRadius: 5,
    width: '75%',
    height: 40,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 15,
  },
  userRegionsListButtonDisabled: {
    borderWidth: 0.5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    borderRadius: 5,
    width: '75%',
    height: 40,
    justifyContent: 'center',
    marginTop: 15,
    alignSelf: 'center',
  },
  passwordButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: '#1890ff',
    borderRadius: 5,
    width: '75%',
    height: 40,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 15,
  },
  disabledPasswordButton: {
    borderWidth: 0.5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    borderRadius: 5,
    width: '75%',
    height: 40,
    justifyContent: 'center',
    marginTop: 15,
    alignSelf: 'center',
  },
  passwordButtonContainer: {
    width: '100%',
    // height: 400,
  },
  passwordButtonContainerDisabled: {
    width: '100%',
  },
  calendarContainer: {
    marginRight: 30,
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 4,
  },
  previousTitleTextStyle: {
    fontWeight: 'bold',
  },
  nextTitleTextStyle: {
    fontWeight: 'bold',
  },
  changePasswordContainer: {
    width: '100%',
    marginTop: 20,
  },
  changePasswordInputTextLight: {
    paddingTop: 3,
    fontSize: 15,
    width: 180,
    color: '#606060',
    fontWeight: 'bold',
  },
  changePasswordInputTextDark: {
    paddingTop: 3,
    fontSize: 15,
    width: 180,
    color: 'white',
    fontWeight: 'bold',
  },
  subscribersListContainer: {
    alignSelf: 'center',
    marginTop: 10,
    width: '100%',
  },
  regionListButtonLight: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    width: '70%',
    height: 30,
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
  },
  regionListButtonDarK: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    width: '100%',
    height: 30,
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
    backgroundColor: 'white',
  },
  userRegionsButtonLight: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    width: '100%',
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
  },
  userRegionsButtonDark: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    width: '100%',
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
    backgroundColor: 'white',
  },
  regionListText: {},
  regionListTextHolder: {
    width: '70%',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },
  regionListDot: {
    color: 'red',
    fontSize: 16,
    fontWeight: 'bold',
  },
  regionListTextLight: {
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 5,
    color: '#606060',
  },
  regionListTextDark: {
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 5,
    color: 'white',
  },
  countryListHolder: {
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 5,
    backgroundColor: 'white',
    height: 150,
    width: '80%',
    alignSelf: 'center',
  },
  countryListHolderDark: {},
  countryButton: {
    marginTop: 5,
    paddingLeft: 15,
  },
  changeThemeContainer: {
    right: 10,
  },
  changeThemeButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: 'white',
    borderRadius: 5,
    height: 40,
    justifyContent: 'center',
  },
  changeThemeButtonText: {
    color: '#1890ff',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  savePasswordButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: 'white',
    borderRadius: 5,
    width: '90%',
    height: 40,
    justifyContent: 'center',
    marginTop: 10,
  },
  userSubscribersRegionListHolder: {
    flexDirection: 'row',
    backgroundColor: '#1890ff',
    borderColor: '#1890ff',
    marginTop: 5,
    // width: '85%',
    height: 25,
    borderWidth: 1,
    borderRadius: 5,
    justifyContent: 'center',
  },
  regionText: {
    alignSelf: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 13,
  },
  cancelIcon: {
    padding: 2,
  },
  regionButtonsHolder: {
    flexDirection: 'row',
    marginTop: 10,
  },
  addRegionButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: 'white',
    borderRadius: 5,
    width: '25%',
    height: 30,
    justifyContent: 'center',
    marginLeft: '40%',
  },
  addRegionButtonText: {
    color: '#1890ff',
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: '#ff4d4f',
    borderColor: '#ff4d4f',
    borderWidth: 1,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    height: 30,
    width: '25%',
    marginLeft: '5%',
  },
  cancelText: {
    color: 'white',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  birthdayInput: {
    width: '11%',
    paddingLeft: 5,
  },
});

export default styles;
