import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  subscribersListContainer: {
    alignSelf: 'center',
    marginTop: 10,
    width: '100%',
  },
  regionListButtonLight: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    width: '70%',
    height: 30,
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
  },
  regionListButtonDarK: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    width: '100%',
    height: 30,
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
    backgroundColor: 'white',
  },
  userRegionsButtonLight: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: 'rgb(215,215,215)',
    width: '100%',
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
  },
  userRegionsButtonDark: {
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'gray',
    width: '100%',
    marginTop: 5,
    marginRight: 10,
    padding: 5,
    alignSelf: 'center',
    backgroundColor: 'white',
  },
  regionListText: {},
  regionListTextHolder: {
    width: '70%',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },
  regionListDot: {
    color: 'red',
    fontSize: 16,
    fontWeight: 'bold',
  },
  regionListTextLight: {
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 5,
    color: '#606060',
  },
  regionListTextDark: {
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 5,
    color: 'white',
  },
  countryListHolder: {
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 5,
    backgroundColor: 'white',
    height: 150,
    width: '80%',
    alignSelf: 'center',
  },
  countryListHolderDark: {},
  countryButton: {
    marginTop: 5,
    paddingLeft: 15,
  },

  userSubscribersRegionListHolder: {
    flexDirection: 'row',
    backgroundColor: '#1890ff',
    borderColor: '#1890ff',
    marginTop: 5,
    // width: '85%',
    height: 25,
    borderWidth: 1,
    borderRadius: 5,
    justifyContent: 'center',
  },
  regionText: {
    alignSelf: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 13,
  },
  cancelIcon: {
    padding: 2,
  },
  regionButtonsHolder: {
    flexDirection: 'row',
    marginTop: 10,
  },
  addRegionButton: {
    borderWidth: 1,
    borderColor: '#1890ff',
    backgroundColor: 'white',
    borderRadius: 5,
    width: '25%',
    height: 30,
    justifyContent: 'center',
    marginLeft: '40%',
  },
  addRegionButtonText: {
    color: '#1890ff',
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: '#ff4d4f',
    borderColor: '#ff4d4f',
    borderWidth: 1,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    height: 30,
    width: '25%',
    marginLeft: '5%',
  },
  cancelText: {
    color: 'white',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
});

export default styles;
